### ISSUE TITLE
NA Player Search Fails

### ISSUE THREAD

**Issue by Stevoni** [Rembel/wotdossier#42]
When looking up a player for the US region, the player search times out. Tried both the installer from res-mods and the code build and received the error in both.

Looks like the app id is defaulting to "demo", but works for RU and EU. Do you have an app id for the NA server?

Looks like this can be worked around by having an account on EU or RU cluster and selecting that for the settings screen then switching it back once the username validation passes.

**Comment by Rembel** [comment]
for us region program has incorrect settings
in app.settings change value for param "Server" to "com"
in WotDossier.exe.config change
<add key="app_id.us" value="demo" />
to
<add key="app_id.com" value="demo" />
Will be fixed in future version
possible regions ru, eu, com(usa), kr, asia
